### PR TITLE
Bugfix/group test

### PR DESCRIPTION
**Pull request by zhangjiangqige**
Fix `java.lang.NoSuchFieldError: ANNOTATION_PROCESSOR_MODULE_PATH` when running tests. This should fix the Travis job "group=test".

The root cause of the failure is that jsr308-langtools includes many core classes of java, including `javax.*`. While building the projects jsr308-langtools and annotation-tools are fine, running them could lead to the conflict between the packages in JRE in the environment (rt.jar) and the packages in jsr308-langtools.

In this case, `ANNOTATION_PROCESSOR_MODULE_PATH` is a new JDK9 field introduced to `javax.tools.StandardLocation`, which can be found at [eisop/jsr308-langtools](https://bitbucket.org/eisop/jsr308-langtools/src/d39221f315e7ba680d09b50b7f0ba541758f4ed0/src/java.compiler/share/classes/javax/tools/StandardLocation.java?at=default&fileviewer=file-view-default#StandardLocation.java-65). Since it does not exist in JDK8, and the rt.jar of JDK8, which is in bootclasspath, is in the front of the user classpath when loading classes, the tests fail.

However this kind of fix (-Xbootclasspath) should be cautious to incorporate due to potential legal/license breaching issues when using Oracle JDK according to [stackoverflow](https://stackoverflow.com/a/33631635) and the [official doc](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html).

Somewhat related https://github.com/typetools/checker-framework/issues/1739.

### CODE REVIEW

**Comment by wmdietl** [comment]
Thanks for tracking this down!
Can you guard all uses of `-Xbootclasspath` with a check for whether a Java 8 JVM is used? (Also change the existing use in `annotation-file-utilities/tests/enum-imports/Makefile`)
That is, add a new variable that contains the `-Xbootclasspath` text only if a Java 8 JVM is used.
Can you manually try whether the tests then build on a Java 9+ JVM?

**Comment by wmdietl** [comment]
There is another use of bootclasspath here: https://github.com/eisop/annotation-tools/blob/master/scene-lib/build.xml#L185
These should be changed to something similar to the conditional logic here: https://github.com/eisop/checker-framework/blob/master/build.gradle#L147

**Comment by zhangjiangqige** [comment]
I didn't add a new variable to `annotation-file-utilities/build.xml` since it doesn't seem to be telling [annotation-file-utilities/tests/Makefile](https://github.com/eisop/annotation-tools/blob/02cac2a8e52551bbbed1fe7598930ca3cbb35e47/annotation-file-utilities/tests/Makefile#L16) which java to use; I guess it may be reasonable to keep letting Makefile control this by itself?

And tests using JDK 9+ did reveal some problems...
1. [annotation-file-utilities/tests/system-test](https://github.com/eisop/annotation-tools/blob/02cac2a8e52551bbbed1fe7598930ca3cbb35e47/annotation-file-utilities/tests/system-test/Makefile#L32) now generates jaif files with slightly different content (but still looks correct; just some numbers differed). Should I create multi-versioned expected jaif?
2. [annotation-file-utilities/tests/abbreviated/C1.java](https://github.com/eisop/annotation-tools/blob/02cac2a8e52551bbbed1fe7598930ca3cbb35e47/annotation-file-utilities/tests/abbreviated/C1.java#L1) couldn't be compiled because the module `java.xml.ws.annotation` which contains `javax.annotation` needs to be added by using `--add-modules java.xml.ws.annotation` when compiling and running for JDK9/10. This module is further removed since JDK 11 and to use it we need to add another dependency `javax.annotation-api`.
3. the tests of scene-lib is also outputting slightly different annotations

I'll inspect them later.

**Comment by wmdietl** [comment]
Something doesn't seem to be right yet, as the project no longer compiles with Java 8. Can you get the Travis tests passing?

Regarding `system-test`: I don't think we would want to add multiple versions of test files. Can you first determine what order is changing? Maybe it is enough to sort something to get consistent behavior between versions.

Regarding `C1.java`: It looks like it is completely arbitrary that `javax.annotation.Resource` is used in that test. Can you change the test to use `@Regex` from the Checker Framework?

Regarding scence-lib tests: let's determine what is different and how we can fix that.

**Comment by zhangjiangqige** [comment]
> Something doesn't seem to be right yet, as the project no longer compiles with Java 8. Can you get the Travis tests passing?

This is because the build file first looked for jsr308-langtools under my username on bitbucket, which did not exist, and then used the default typetools version. Now I forked eisop/jsr308-langtools on bitbucket and the test should succeed as normal.

> Regarding `system-test`: I don't think we would want to add multiple versions of test files. Can you first determine what order is changing? Maybe it is enough to sort something to get consistent behavior between versions.

Some [offsets in asmx/src/org/objectweb/asmx/ClassReader.java](https://github.com/eisop/annotation-tools/blob/02cac2a8e52551bbbed1fe7598930ca3cbb35e47/asmx/src/org/objectweb/asmx/ClassReader.java#L1502) are different between JDK 8 and 9. I'll need more time to debug this.

> Regarding `C1.java`: It looks like it is completely arbitrary that `javax.annotation.Resource` is used in that test. Can you change the test to use `@Regex` from the Checker Framework?

Sorry I'm not sure where to use `@Regex` since there are no strings in `C1.java`... but removing the import worked. This is in the latest commit.

> Regarding scence-lib tests: let's determine what is different and how we can fix that.

After some more inspection I believe this is because of the difference of the "attributes" of annotations between JDK 8 and 9+ ([@Deprecated](https://github.com/eisop/annotation-tools/blob/02cac2a8e52551bbbed1fe7598930ca3cbb35e47/scene-lib/test/annotations/tests/classfile/cases/package-info.java#L1) in this case), which scene-lib cares.

Since JDK 9, `@Target` can be used with `MODULE` ([doc](https://docs.oracle.com/javase/9/docs/api/java/lang/annotation/Target.html)), and two new elements `since` and `removal` were added to `@Deprecated` ([doc](https://docs.oracle.com/javase/9/docs/api/java/lang/Deprecated.html)); these lead to the extra output of scene-lib that's causing the failure of the test.

Specifically the test compares the annotations read from [package-info.jaif](https://github.com/eisop/annotation-tools/blob/master/scene-lib/test/annotations/tests/classfile/cases/package-info.jaif) and [package-info.class](https://github.com/eisop/annotation-tools/blob/master/scene-lib/test/annotations-expected/tests/classfile/cases/package-info.class). However the class file doesn't contain any information related to `@Target`, but `@Target` is added to the output with the default value which includes `MODULE` if it's JDK 9+. Perhaps we can generate a new class file and explicitly declare `@Target` without `MODULE`? But I'm not sure if this kind of compromise is fine.

**Comment by wmdietl** [comment]
Regarding jsr308-langtools: I think for now we can change https://github.com/eisop/annotation-tools/blob/master/.travis-build-without-test.sh#L37 from `typetools` to `eisop` to prevent this from happening to anyone else.

The specific annotations usually don't matter for the test cases, just where they are inserted and expected. So you can probably change the C1 test to use `@Regex` instead of the missing annotation.
Similarly, instead of the changed `@Deprecated` you could adapt the test case to use another annotation, possibly something you'll introduce, to make sure the test works in all versions.

I'll need some more time to look at the other issues. Thanks for investigating them!

**Comment by wmdietl** [comment]
Thanks for these improvements! I've merged them, as they make the Java 8 build happy.
Can you continue looking what needs to be changed to also make the Java 9 build work and open new PRs?
But first, can you see why the other projects don't work with Java 8 yet?

**Comment by zhangjiangqige** [comment]
> Thanks for these improvements! I've merged them, as they make the Java 8 build happy.
> Can you continue looking what needs to be changed to also make the Java 9 build work and open new PRs?
> But first, can you see why the other projects don't work with Java 8 yet?

Sure.

**Pull request merged**
